In [1]:
import pandas as pd

data = pd.read_csv("../data/netflix-rotten-tomatoes-metacritic-imdb.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15480 entries, 0 to 15479
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  15480 non-null  object
 1   Genre                  13770 non-null  object
 2   Tags                   15413 non-null  object
 3   Languages              13526 non-null  object
 4   Series or Movie        15480 non-null  object
 5   Hidden Gem Score       13379 non-null  float64
 6   Country Availability   15461 non-null  object
 7   Runtime                15479 non-null  object
 8   Director               10772 non-null  object
 9   Writer                 11150 non-null  object
 10  Actors                 13555 non-null  object
 11  View Rating            8456 non-null   object
 12  IMDb Score             13381 non-null  float64
 13  Rotten Tomatoes Score  6382 non-null   float64
 14  Metacritic Score       4336 non-null   float64
 15  Awards Received        6075 non-null   float64
 16  Awards Nominated For   7661 non-null   float64
 17  Boxoffice              4007 non-null   object
 18  Release Date           13373 non-null  object
 19  Netflix Release Date   15480 non-null  object
 20  Production House       5149 non-null   object
 21  Netflix Link           15480 non-null  object
 22  IMDb Link              13177 non-null  object
 23  Summary                15471 non-null  object
 24  IMDb Votes             13379 non-null  float64
 25  Image                  15480 non-null  object
 26  Poster                 11842 non-null  object
 27  TMDb Trailer           7194 non-null   object
 28  Trailer Site           7194 non-null   object
dtypes: float64(7), object(22)
memory usage: 3.4+ MB

In [2]:
data.isnull().sum()

Title                        0
Genre                     1710
Tags                        67
Languages                 1954
Series or Movie              0
Hidden Gem Score          2101
Country Availability        19
Runtime                      1
Director                  4708
Writer                    4330
Actors                    1925
View Rating               7024
IMDb Score                2099
Rotten Tomatoes Score     9098
Metacritic Score         11144
Awards Received           9405
Awards Nominated For      7819
Boxoffice                11473
Release Date              2107
Netflix Release Date         0
Production House         10331
Netflix Link                 0
IMDb Link                 2303
Summary                      9
IMDb Votes                2101
Image                        0
Poster                    3638
TMDb Trailer              8286
Trailer Site              8286
dtype: int64

In [3]:
data.drop(columns=['Netflix Link', 'IMDb Link', 'Summary', 'Image', 'Poster', 'TMDb Trailer'], inplace=True)
data.dropna(subset=['Genre','Tags','Languages','Director'], inplace=True)

In [4]:
data.isnull().sum()

Title                       0
Genre                       0
Tags                        0
Languages                   0
Series or Movie             0
Hidden Gem Score          262
Country Availability       16
Runtime                     0
Director                    0
Writer                    608
Actors                    126
View Rating              3836
IMDb Score                261
Rotten Tomatoes Score    4248
Metacritic Score         6224
Awards Received          5517
Awards Nominated For     4283
Boxoffice                6550
Release Date              220
Netflix Release Date        0
Production House         5438
IMDb Votes                262
Trailer Site             3441
dtype: int64

In [5]:
data

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Production House,IMDb Votes,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,98.0,82.0,74.0,57.0,"$2,122,065",12 Dec 2008,2021-03-04,"Canal+, Sandrew Metronome",205926.0,NaN
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,79.0,69.0,1.0,NaN,"$70,632",08 May 2020,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",2838.0,YouTube
2,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon",...,NaN,46.0,NaN,NaN,"$16,263",28 Aug 2020,2021-03-04,NaN,1720.0,YouTube
4,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,NaN,...,NaN,NaN,NaN,4.0,NaN,22 Sep 2011,2021-03-04,NaN,63.0,NaN
5,The Con-Heartist,"Comedy, Romance","Romantic Comedies,Comedies,Romantic Films,Thai...",Thai,Movie,8.6,Thailand,> 2 hrs,Mez Tharatorn,"Pattaranad Bhiboonsawade, Thodsapon Thiptinnak...",...,NaN,NaN,NaN,NaN,NaN,03 Dec 2020,2021-03-03,NaN,131.0,YouTube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15464,District 13: Ultimatum,"Action, Crime, Thriller","International Movies,Action Thrillers,French F...","French, English",Movie,3.4,France,1-2 hour,Patrick Alessandrin,Luc Besson,...,75.0,64.0,NaN,1.0,"$36,136",18 Feb 2009,2015-04-14,NaN,42967.0,YouTube
15465,13 Going on 30,"Comedy, Fantasy, Romance","Romantic Comedies,Comedies,Romantic Films,Roma...","English, Portuguese",Movie,3.1,"Hungary,Lithuania,Romania,United Kingdom,Belgi...",1-2 hour,Gary Winick,"Josh Goldsmith, Cathy Yuspa",...,65.0,57.0,NaN,11.0,"$57,231,747",23 Apr 2004,2015-04-14,"Revolution Studios, Thirteen Productions LLC",167842.0,YouTube
15466,LIFE 2.0,Documentary,"Social & Cultural Documentaries,Biographical D...",English,Movie,8.2,"Hungary,Lithuania,India,Australia,United Kingd...",1-2 hour,Jason Spingarn-Koff,NaN,...,89.0,65.0,1.0,NaN,NaN,22 Jan 2010,2015-04-14,NaN,878.0,NaN
15467,Brand New Day,"Documentary, Music","Australian Comedies,Romantic Comedies,Australi...",English,Movie,8.6,Australia,1-2 hour,Amos Gitai,NaN,...,NaN,NaN,NaN,NaN,NaN,17 Sep 1988,2015-04-14,NaN,14.0,NaN
15473,Daniel Arends: Blessuretijd,Comedy,"Stand-up Comedy,International Movies,Comedies",Dutch,Movie,8.8,Belgium,1-2 hour,Doesjka van Hoogdalem,Daniël Arends,...,NaN,NaN,NaN,NaN,NaN,13 Jan 2012,2015-04-14,NaN,174.0,NaN

# Récupération date de sortie netflix avec l'API IMDb gratuite

In [ ]:
import requests
from Keys_APIs import get_API_key_TMDb

API_KEY = get_API_key_TMDb()

def get_release_date_tmdb(title):
    try:
        # Étape 1 : recherche du film par titre
        search_url = "https://api.themoviedb.org/3/search/movie"
        params = {
            "api_key": API_KEY,
            "query": title
        }
        response = requests.get(search_url, params=params).json()
        results = response.get("results")
        if not results:
            return None

        # Prend le premier résultat
        movie_id = results[0]['id']

        # Étape 2 : Récupération des dates de sortie
        release_url = f"https://api.themoviedb.org/3/movie/{movie_id}/release_dates"
        release_response = requests.get(release_url, params={"api_key": API_KEY}).json()
        releases = release_response.get("results", [])

        # Recherche la date pour US ou mondial
        for country_data in releases:
            if country_data['iso_3166_1'] in ['US', 'FR', 'GB']:
                for entry in country_data['release_dates']:
                    return entry['release_date'][:10]  # format 'YYYY-MM-DD'

        return None

    except Exception as e:
        print(f"Erreur pour {title}: {e}")
        return None

print(get_release_date_tmdb("The Irishman"))

2019-10-15

In [7]:
for idx, row in data[data['Release Date'].isna()].iterrows():
    title = row['Title']
    date = get_release_date_tmdb(title)
    data.at[idx, 'Release Date'] = date

In [8]:
data.fillna({
    'Hidden Gem Score': -1,
    'Country Availability': "Unknown",
    'Writer': "Unknown",
    'Actors': "Unknown",
    'View Rating': "Uknown",
    'IMDb Score': data['IMDb Score'].mean(),
    'Rotten Tomatoes Score': data['Rotten Tomatoes Score'].mean(),
    'Metacritic Score': data['Metacritic Score'].mean(),
    'Awards Received': 0,
    'Awards Nominated For': 0,
    'Boxoffice': "$0",
    'Production House': "Unknown",
    'IMDb Votes': data['IMDb Votes'].mean(),
    'Trailer Site': "Unknown"
}, inplace=True)

In [9]:
data.isnull().sum()

Title                      0
Genre                      0
Tags                       0
Languages                  0
Series or Movie            0
Hidden Gem Score           0
Country Availability       0
Runtime                    0
Director                   0
Writer                     0
Actors                     0
View Rating                0
IMDb Score                 0
Rotten Tomatoes Score      0
Metacritic Score           0
Awards Received            0
Awards Nominated For       0
Boxoffice                  0
Release Date             113
Netflix Release Date       0
Production House           0
IMDb Votes                 0
Trailer Site               0
dtype: int64

In [21]:
data.dropna(subset=['Release Date'], inplace=True)
data.shape

(10422, 23)

In [22]:
from datetime import datetime

def convert_date_format(date_str):
    try:
        return datetime.strptime(date_str, "%d %b %Y").strftime("%Y-%m-%d")
    except:
        return date_str

data['Release Date'] = data['Release Date'].apply(convert_date_format)

In [19]:
data

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Production House,IMDb Votes,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,98.000000,82.000000,74.0,57.0,"$2,122,065",2008-12-12,2021-03-04,"Canal+, Sandrew Metronome",205926.0,Unknown
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,79.000000,69.000000,1.0,0.0,"$70,632",2020-05-08,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",2838.0,YouTube
2,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon",...,59.466836,46.000000,0.0,0.0,"$16,263",2020-08-28,2021-03-04,Unknown,1720.0,YouTube
4,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,Unknown,...,59.466836,56.797263,0.0,4.0,$0,2011-09-22,2021-03-04,Unknown,63.0,Unknown
5,The Con-Heartist,"Comedy, Romance","Romantic Comedies,Comedies,Romantic Films,Thai...",Thai,Movie,8.6,Thailand,> 2 hrs,Mez Tharatorn,"Pattaranad Bhiboonsawade, Thodsapon Thiptinnak...",...,59.466836,56.797263,0.0,0.0,$0,2020-12-03,2021-03-03,Unknown,131.0,YouTube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15464,District 13: Ultimatum,"Action, Crime, Thriller","International Movies,Action Thrillers,French F...","French, English",Movie,3.4,France,1-2 hour,Patrick Alessandrin,Luc Besson,...,75.000000,64.000000,0.0,1.0,"$36,136",2009-02-18,2015-04-14,Unknown,42967.0,YouTube
15465,13 Going on 30,"Comedy, Fantasy, Romance","Romantic Comedies,Comedies,Romantic Films,Roma...","English, Portuguese",Movie,3.1,"Hungary,Lithuania,Romania,United Kingdom,Belgi...",1-2 hour,Gary Winick,"Josh Goldsmith, Cathy Yuspa",...,65.000000,57.000000,0.0,11.0,"$57,231,747",2004-04-23,2015-04-14,"Revolution Studios, Thirteen Productions LLC",167842.0,YouTube
15466,LIFE 2.0,Documentary,"Social & Cultural Documentaries,Biographical D...",English,Movie,8.2,"Hungary,Lithuania,India,Australia,United Kingd...",1-2 hour,Jason Spingarn-Koff,Unknown,...,89.000000,65.000000,1.0,0.0,$0,2010-01-22,2015-04-14,Unknown,878.0,Unknown
15467,Brand New Day,"Documentary, Music","Australian Comedies,Romantic Comedies,Australi...",English,Movie,8.6,Australia,1-2 hour,Amos Gitai,Unknown,...,59.466836,56.797263,0.0,0.0,$0,1988-09-17,2015-04-14,Unknown,14.0,Unknown
15473,Daniel Arends: Blessuretijd,Comedy,"Stand-up Comedy,International Movies,Comedies",Dutch,Movie,8.8,Belgium,1-2 hour,Doesjka van Hoogdalem,Daniël Arends,...,59.466836,56.797263,0.0,0.0,$0,2012-01-13,2015-04-14,Unknown,174.0,Unknown

In [23]:
data.to_csv('../data/netflix_data.csv', index=False, encoding='utf-8-sig')